var searchData=
[
  ['s_20eye_20view_0',['Bird&apos;s Eye View',['../ui_birds-eye.html',1,'ui']]],
  ['s_20special_20about_20it_1',['What&apos;s special about it?',['../index.html#ab_special',1,'']]],
  ['schema_20qm7_20xsd_2',['XML Schema (qm7.xsd)',['../ui_model_file.html#ui_model_xsd',1,'']]],
  ['scheme_3',['Scheme',['../ui_scheme.html#ui_scheme-dark',1,'Dark Color Scheme'],['../ui_scheme.html#ui_scheme-forced',1,'Forced Color Scheme'],['../ui_scheme.html#ui_scheme-light',1,'Light Color Scheme']]],
  ['schemes_4',['Light and Dark Color Schemes',['../ui_scheme.html',1,'ui']]],
  ['scope_5',['Class Declaration in C (File Scope)',['../ce_declare.html#ce_declare_class-c-static',1,'']]],
  ['scratch_6',['Creating A New Model from Scratch',['../gs_tut.html#gs_tut_new',1,'']]],
  ['scrolling_20diagrams_7',['Scrolling Diagrams',['../bm_diagram.html#bm_diagram_scroll',1,'']]],
  ['scrolling_20with_20the_20keyboard_8',['Scrolling with the Keyboard',['../bm_diagram.html#bm_diagram_scroll_with_keyboard',1,'']]],
  ['scrolling_20with_20the_20mouse_20wheel_9',['Scrolling with the Mouse Wheel',['../bm_diagram.html#bm_diagram_scroll_with_wheel',1,'']]],
  ['search_10',['Model Search',['../ui_search.html',1,'ui']]],
  ['search_20menu_11',['Search Menu',['../ui_menus.html#ui_menu_search',1,'']]],
  ['search_20replace_12',['Search/Replace',['../bm_search.html',1,'bm']]],
  ['searchview_20section_13',['SearchView Section',['../ui_custom.html#ui_custom_search',1,'']]],
  ['section_14',['Section',['../ui_custom.html#ui_custom_code',1,'CodeEdit Section'],['../ui_custom.html#ui_custom_diagram',1,'DiagramView Section'],['../ui_custom.html#ui_custom_doc',1,'DocEdit Section'],['../ui_custom.html#ui_custom_explorer',1,'ExplorerView Section'],['../ui_custom.html#ui_custom_log',1,'Log Section'],['../ui_custom.html#ui_custom_mainwindow',1,'MainWindow Section'],['../ui_custom.html#ui_custom_search',1,'SearchView Section']]],
  ['segment_15',['Adding A Choice Segment',['../sm_choice.html#sm_choice_add',1,'']]],
  ['segment_20property_20sheet_16',['Choice Segment Property Sheet',['../sm_choice.html#sm_choice_prop',1,'']]],
  ['segments_17',['Segments',['../sm_choice.html#sm_choice_nest',1,'Nested Choice Segments'],['../sm_choice.html#sm_choice_routing',1,'Routing Choice Segments'],['../sm_choice.html',1,'Working with Choice Segments']]],
  ['segments_20without_20else_18',['Choice Segments Without else',['../sm_choice.html#sm_choice_none',1,'']]],
  ['select_20tool_19',['The Select Tool',['../ui_toolbox.html#ui_toolbox_select',1,'']]],
  ['selected_20shapes_20',['Moving the Selected Shapes',['../bm_diagram.html#bm_diagram_shape_move',1,'']]],
  ['selecting_20diagram_20shapes_21',['Selecting Diagram Shapes',['../bm_diagram.html#bm_diagram_shape_select',1,'']]],
  ['selecting_20shapes_20with_20the_20lasso_22',['Selecting Shapes with the Lasso',['../bm_diagram.html#bm_diagram_shape_select-lasso',1,'']]],
  ['selecting_20shapes_20with_20the_20mouse_20toggle_23',['Selecting Shapes with the Mouse-Toggle',['../bm_diagram.html#bm_diagram_shape_select-mouse',1,'']]],
  ['sequentially_24',['Reading Online Help Sequentially',['../help.html#help_seq',1,'']]],
  ['session_20file_25',['QM Session File',['../ui_session_file.html',1,'ui']]],
  ['setting_20environment_20variables_26',['Setting Environment Variables',['../ui_tools-dlg.html#ui_tools-dlg_env',1,'']]],
  ['setting_20file_20association_20for_20qm_20models_27',['Setting File Association for QM Models',['../gs_run.html#gs_run_linux_file',1,'']]],
  ['setting_20the_20directory_20path_28',['Setting the Directory Path',['../ce_dir.html#ce_dir_path',1,'']]],
  ['setup_20of_20qm_20desktop_20shortcut_29',['Manual Setup of QM Desktop Shortcut',['../gs_get.html#gs_install_linux_icon',1,'']]],
  ['shallow_30',['Is Shallow',['../sm_hist.html#sm_hist-is_shallow',1,'']]],
  ['shapes_31',['Shapes',['../bm_diagram.html#bm_diagram_shape_move',1,'Moving the Selected Shapes'],['../bm_diagram.html#bm_diagram_shape_select',1,'Selecting Diagram Shapes']]],
  ['shapes_20with_20the_20lasso_32',['Selecting Shapes with the Lasso',['../bm_diagram.html#bm_diagram_shape_select-lasso',1,'']]],
  ['shapes_20with_20the_20mouse_20toggle_33',['Selecting Shapes with the Mouse-Toggle',['../bm_diagram.html#bm_diagram_shape_select-mouse',1,'']]],
  ['sheet_34',['Sheet',['../sm_choice.html#sm_choice_prop',1,'Choice Segment Property Sheet'],['../bm_attr.html#bm_attr-class-prop',1,'Class Attribute Property Sheet'],['../bm_oper-class.html#bm_class-oper-prop',1,'Class Operation Property Sheet'],['../bm_class.html#bm_class_prop',1,'Class Property Sheet'],['../ce_dir.html#ce_dir_prop',1,'Directory Property Sheet'],['../ce_file.html#ce_file_prop',1,'File Property Sheet'],['../bm_attr.html#bm_attr-free-prop',1,'Free Attribute Property Sheet'],['../bm_oper-free.html#bm_free-oper-prop',1,'Free Operation Property Sheet'],['../sm_init.html#sm_init_prop',1,'Initial Transition Property Sheet'],['../bm_model.html#bm_model_prop',1,'Model Property Sheet'],['../bm_package.html#bm_package_prop',1,'Package Property Sheet'],['../sm_state.html#sm_state_prop',1,'State Property Sheet'],['../sm_statechart.html#sm_statechart_prop',1,'Statechart Property Sheet'],['../sm_tran.html#sm_tran_prop',1,'Transition Property Sheet'],['../sm_hist.html#sm_hist_prop',1,'Transition to History Property Sheet']]],
  ['sheet_20example_35',['Property Sheet Example',['../ui_prop.html#ui_prop_example',1,'']]],
  ['sheets_36',['Sheets',['../ui_custom.html#ui_custom_qss',1,'QM Style Sheets'],['../ui_prop.html#ui_prop_spec',1,'Specific Property Sheets']]],
  ['shoot_20game_20example_37',['&quot;Fly &apos;n&apos; Shoot&quot; Game Example',['../gs_exa.html#game',1,'']]],
  ['shortcut_38',['Manual Setup of QM Desktop Shortcut',['../gs_get.html#gs_install_linux_icon',1,'']]],
  ['showing_20hiding_20docks_20amp_20toolbars_39',['Showing/Hiding Docks &amp;amp; Toolbars',['../ui_dock.html#ui_docs_show',1,'']]],
  ['signals_40',['Signals',['../bm_evt.html#bm_evt-sig',1,'Event Signals'],['../ui_log.html#ui_log-signals',1,'Listing State Signals']]],
  ['sm_2edox_41',['sm.dox',['../sm_8dox.html',1,'']]],
  ['source_20code_42',['Source Code',['../qt_lgpl.html#qt_lgpl-source',1,'Qt Library Source Code'],['../qt_lgpl.html#qt_lgpl_offer',1,'Written Offer to Provide Source Code']]],
  ['source_20projects_43',['Source Projects',['../ui_license-dlg.html#ui_license-closed',1,'Closed Source Projects'],['../ui_license-dlg.html#ui_license-open',1,'Open Source Projects']]],
  ['special_20about_20it_44',['What&apos;s special about it?',['../index.html#ab_special',1,'']]],
  ['specific_20default_20actions_45',['Item-Specific Default Actions',['../ui_explorer.html#ui_explorer_default',1,'']]],
  ['specific_20popup_20menus_46',['Item-Specific Popup Menus',['../ui_explorer.html#ui_explorer_popup',1,'']]],
  ['specific_20property_20sheets_47',['Specific Property Sheets',['../ui_prop.html#ui_prop_spec',1,'']]],
  ['spexygen_20on_20github_48',['Spexygen on GitHub',['../help.html#hel_spexygen',1,'']]],
  ['stack_49',['The Undo/Redo Stack',['../bm_undo-redo.html#bm_undo_stack',1,'']]],
  ['stack_20depth_20limit_50',['Undo/Redo Stack Depth Limit',['../bm_undo-redo.html#bm_undo_limit',1,'']]],
  ['started_51',['Getting Started',['../gs.html',1,'']]],
  ['state_52',['State',['../sm_state.html#sm_state_add',1,'Adding a State'],['../sm_hist.html#sm_hist_add',1,'Adding History to a Composite State'],['../sm_state.html#sm_state_delete',1,'Deleting a State'],['../sm_state.html#sm_state_move',1,'Moving a State'],['../sm_state.html#sm_state_resize',1,'Resizing a State'],['../ce_define1.html#ce_define1-state',1,'State']]],
  ['state_20documentation_53',['State Documentation',['../sm_state.html#sm_state-doc',1,'']]],
  ['state_20entry_20action_54',['State Entry Action',['../sm_state.html#sm_state-entry',1,'']]],
  ['state_20exit_20action_55',['State Exit Action',['../sm_state.html#sm_state-exit',1,'']]],
  ['state_20history_56',['Adding Incoming Transition to State History',['../sm_hist.html#sm_hist_in',1,'']]],
  ['state_20machine_57',['State Machine',['../gs_tut.html#gs_tut_add-sm',1,'Add State Machine'],['../ce_define1.html#ce_define1-sm',1,'State Machine']]],
  ['state_20machine_20base_20classes_58',['State Machine Base Classes',['../sm.html#sm_class',1,'']]],
  ['state_20machine_20constructor_59',['State Machine Constructor',['../ce_sm.html#ce_sm_ctor',1,'']]],
  ['state_20machine_20constructor_20in_20c_60',['State Machine Constructor in C',['../ce_sm.html#ce_sm_ctor-c',1,'State Machine Constructor in C'],['../ce_sm.html#ce_sm_ctor-cpp',1,'State Machine Constructor in C++']]],
  ['state_20machine_20diagram_61',['State Machine Diagram',['../gs_tut.html#gs_tut_draw',1,'Drawing State Machine Diagram'],['../sm_statechart.html#sm_resize',1,'Resizing a State Machine Diagram']]],
  ['state_20machine_20implementation_62',['Changing State Machine Implementation',['../sm.html#sm_class-change',1,'']]],
  ['state_20machine_20toolbox_63',['State Machine Toolbox',['../sm.html#sm_toolbox',1,'']]],
  ['state_20machines_64',['State Machines',['../ce_sm.html',1,'Generating Code for State Machines'],['../sm.html#sm_class_qhsm',1,'QHsm-Based State Machines'],['../sm.html#sm_class_qmsm',1,'QMsm/QMActive-Based State Machines'],['../sm.html',1,'State Machines']]],
  ['state_20machines_20in_20qm_65',['Hierarchical State Machines in QM',['../sm.html#sm_hsm',1,'']]],
  ['state_20name_66',['State Name',['../sm_state.html#sm_state-name',1,'']]],
  ['state_20property_20sheet_67',['State Property Sheet',['../sm_state.html#sm_state_prop',1,'']]],
  ['state_20signals_68',['Listing State Signals',['../ui_log.html#ui_log-signals',1,'']]],
  ['state_20to_20state_20transition_69',['Adding State-to-State Transition',['../sm_tran.html#sm_tran_add-state',1,'']]],
  ['state_20transition_70',['Adding State-to-State Transition',['../sm_tran.html#sm_tran_add-state',1,'']]],
  ['statechart_71',['Adding a Statechart',['../sm_statechart.html#sm_add',1,'']]],
  ['statechart_20property_20sheet_72',['Statechart Property Sheet',['../sm_statechart.html#sm_statechart_prop',1,'']]],
  ['statecharts_73',['Working with Statecharts',['../sm_statechart.html',1,'sm']]],
  ['states_74',['States',['../gs_tut.html#gs_tut_draw-state',1,'Add States'],['../ce_cond.html#ce_cond_state',1,'Conditional States'],['../ce_cond.html#ce_cond_state_nest',1,'Nesting Conditional States'],['../sm_state.html#sm_state_nest',1,'Nesting of States'],['../sm_state.html',1,'Working with States']]],
  ['states_20transitions_75',['Rendering Conditional States/Transitions',['../ce_cond.html#ce_cond_render',1,'']]],
  ['states_20with_20history_76',['Conditional States with History',['../ce_cond.html#ce_cond_state_hist',1,'']]],
  ['static_20class_20wide_20operations_77',['Static (Class-Wide) Operations',['../bm_oper-class.html#bm_class-oper-static',1,'']]],
  ['status_20bar_78',['Status Bar',['../ui_status.html#ui_status_diagram',1,'Diagram Status Bar'],['../ui_status.html#ui_status_file',1,'File Status Bar'],['../ui_status.html',1,'Status Bar'],['../bm_diagram.html#bm_diagram_zoom_with_status',1,'Zooming with the Status Bar']]],
  ['stereotype_79',['Package Stereotype',['../bm_package.html#bm_package-stero',1,'']]],
  ['strategies_80',['Implementation Strategies',['../ce_sm.html#ce_sm_stra',1,'']]],
  ['style_81',['QM GUI Style',['../ui_custom.html#ui_custom_style',1,'']]],
  ['style_20sheets_82',['QM Style Sheets',['../ui_custom.html#ui_custom_qss',1,'']]],
  ['styles_83',['Birds-Eye Styles',['../ui_custom.html#ui_custom_beye',1,'']]],
  ['sub_20menu_84',['Recent Models Sub-Menu',['../ui_menus.html#ui_menu_file-recent',1,'']]],
  ['subwindows_20view_85',['Subwindows View',['../ui_mdi.html#ui_mdi_subwindows',1,'']]],
  ['superclass_20of_20a_20class_86',['Superclass of a Class',['../bm_class.html#bm_class-super',1,'']]],
  ['superstate_87',['Superstate',['../sm_state.html#sm_state-super',1,'']]],
  ['svg_88',['Copying active diagram to the Clipboard in SVG',['../bm_diagram.html#bm_diagram_export-Clipboard',1,'']]],
  ['syntax_89',['Syntax',['../ce_gen.html#ce_gen-syntax',1,'General Syntax'],['../ce_cond.html#ce_cond_expr',1,'Pre-processor Expression Syntax']]],
  ['syntax_20highlighting_90',['Syntax Highlighting',['../bm_edit.html#bm_edit-syntax',1,'']]]
];
