var searchData=
[
  ['dark_20color_20scheme_0',['Dark Color Scheme',['../ui_scheme.html#ui_scheme-dark',1,'']]],
  ['dark_20color_20schemes_1',['Light and Dark Color Schemes',['../ui_scheme.html',1,'ui']]],
  ['dark_20mode_20toggle_2',['Dark Mode Toggle',['../help.html#help_dark_mode',1,'']]],
  ['declaration_3',['Declaration',['../ce_declare.html#ce_declare_class',1,'Class Declaration'],['../ce_gen.html#ce_gen-decl',1,'Declaration'],['../ce_declare.html#ce_declare_attr',1,'Free Attribute Declaration'],['../ce_declare.html#ce_declare_oper',1,'Free Operation Declaration'],['../ce_declare.html#ce_declare_package',1,'Package Declaration']]],
  ['declaration_20in_20c_4',['Declaration in C',['../ce_declare.html#ce_declare_class-cpp',1,'Class Declaration in C++'],['../ce_declare.html#ce_declare_attr-c',1,'Free Attribute Declaration in C'],['../ce_declare.html#ce_declare_attr-cpp',1,'Free Attribute Declaration in C++'],['../ce_declare.html#ce_declare_oper-c',1,'Free Operation Declaration in C'],['../ce_declare.html#ce_declare_oper-cpp',1,'Free Operation Declaration in C++']]],
  ['declaration_20in_20c_20file_20scope_5',['Class Declaration in C (File Scope)',['../ce_declare.html#ce_declare_class-c-static',1,'']]],
  ['declaration_20in_20c_20header_20file_6',['Class Declaration in C (Header File)',['../ce_declare.html#ce_declare_class-c',1,'']]],
  ['declarations_20versus_20definitions_7',['Declarations versus Definitions',['../ce_gen.html#ce_decl-def',1,'']]],
  ['declaring_20event_20classes_8',['Declaring Event Classes',['../bm_evt.html#bm_evt-decl',1,'']]],
  ['default_20actions_9',['Item-Specific Default Actions',['../ui_explorer.html#ui_explorer_default',1,'']]],
  ['definition_10',['Definition',['../ce_define.html#ce_def_class',1,'Class Definition'],['../ce_gen.html#ce_gen-def',1,'Definition'],['../ce_define.html#ce_def_free-attr',1,'Free Attribute Definition'],['../ce_define.html#ce_def_free-oper',1,'Free Operation Definition'],['../ce_define.html#ce_def_package',1,'Package Definition']]],
  ['definition_20in_20c_11',['Definition in C',['../ce_define.html#ce_def_class-c',1,'Class Definition in C'],['../ce_define.html#ce_def_class-cpp',1,'Class Definition in C++'],['../ce_define.html#ce_def_free-attr-c',1,'Free Attribute Definition in C'],['../ce_define.html#ce_def_free-attr-cpp',1,'Free Attribute Definition in C++'],['../ce_define.html#ce_def_free-oper-c',1,'Free Operation Definition in C'],['../ce_define.html#ce_def_free-oper-cpp',1,'Free Operation Definition in C++']]],
  ['definitions_12',['Declarations versus Definitions',['../ce_gen.html#ce_decl-def',1,'']]],
  ['deleting_20a_20state_13',['Deleting a State',['../sm_state.html#sm_state_delete',1,'']]],
  ['deleting_20model_20items_14',['Deleting Model Items',['../ui_explorer.html#ui_explorer_delete',1,'']]],
  ['depth_20limit_15',['Undo/Redo Stack Depth Limit',['../bm_undo-redo.html#bm_undo_limit',1,'']]],
  ['design_16',['Design',['../index.html#ab_code',1,'Capturing the Physical Design'],['../ce.html#ce_phys',1,'Physical Design']]],
  ['desktop_20shortcut_17',['Manual Setup of QM Desktop Shortcut',['../gs_get.html#gs_install_linux_icon',1,'']]],
  ['destructors_20in_20c_18',['Destructors in C',['../bm_oper-class.html#bm_class-xtor-c',1,'Class Destructors in C'],['../bm_oper-class.html#bm_class-xtor-cpp',1,'Class Destructors in C++']]],
  ['diagram_19',['Diagram',['../bm_diagram.html#bm_diagram_close',1,'Closing a Diagram'],['../gs_tut.html#gs_tut_draw',1,'Drawing State Machine Diagram'],['../bm_diagram.html#bm_diagram_open',1,'Opening a Diagram'],['../sm_statechart.html#sm_resize',1,'Resizing a State Machine Diagram']]],
  ['diagram_20shapes_20',['Selecting Diagram Shapes',['../bm_diagram.html#bm_diagram_shape_select',1,'']]],
  ['diagram_20status_20bar_21',['Diagram Status Bar',['../ui_status.html#ui_status_diagram',1,'']]],
  ['diagram_20to_20a_20graphic_20file_22',['Exporting Active Diagram to a Graphic File',['../bm_diagram.html#bm_diagram_export-file',1,'']]],
  ['diagram_20to_20the_20clipboard_20in_20svg_23',['Copying active diagram to the Clipboard in SVG',['../bm_diagram.html#bm_diagram_export-Clipboard',1,'']]],
  ['diagram_20toolbox_24',['Diagram Toolbox',['../ui_toolbox.html',1,'ui']]],
  ['diagrams_25',['Diagrams',['../bm_diagram.html#bm_diagram_export',1,'Exporting Diagrams'],['../bm_diagram.html#bm_diagram_pan',1,'Panning Diagrams'],['../bm_diagram.html#bm_diagram_scroll',1,'Scrolling Diagrams'],['../bm_diagram.html',1,'Working with Diagrams'],['../bm_diagram.html#bm_diagram_zoom',1,'Zooming Diagrams']]],
  ['diagramview_20section_26',['DiagramView Section',['../ui_custom.html#ui_custom_diagram',1,'']]],
  ['dialog_20box_27',['Dialog Box',['../ui_license-dlg.html',1,'Code Generation License Dialog Box'],['../ui_tools-dlg.html',1,'Manage Tools Dialog Box'],['../ui_new-dlg.html',1,'New Model Dialog Box']]],
  ['dialog_20box_28',['Opening the Manage Tools dialog box',['../ui_tools-dlg.html#ui_tools-dlg_open',1,'']]],
  ['dining_20philosophers_20problem_20dpp_20example_29',['Dining Philosophers Problem (DPP) Example',['../gs_exa.html#dpp',1,'']]],
  ['directories_30',['Directories',['../ce_dir.html#ce_dir_nest',1,'Nested Directories'],['../ce_dir.html',1,'Working with Directories']]],
  ['directories_20inside_20the_20model_20or_20a_20package_31',['Directories Inside the Model or a Package',['../ce_dir.html#ce_dir_package',1,'']]],
  ['directory_32',['Directory',['../gs_tut.html#gs_tut_ce-dir',1,'Add Directory'],['../ce_dir.html#ce_dir_add',1,'Adding a New Directory']]],
  ['directory_20path_33',['Setting the Directory Path',['../ce_dir.html#ce_dir_path',1,'']]],
  ['directory_20property_20sheet_34',['Directory Property Sheet',['../ce_dir.html#ce_dir_prop',1,'']]],
  ['distribution_35',['Finding the QM Examples in the QP Distribution',['../gs_exa.html#gs_examples_finding',1,'']]],
  ['divider_20comments_36',['Divider Comments',['../ce_comment.html#ce_comment-div',1,'']]],
  ['do_37',['What does it do?',['../index.html#ab_goals',1,'']]],
  ['docedit_20section_38',['DocEdit Section',['../ui_custom.html#ui_custom_doc',1,'']]],
  ['dock_20windows_39',['Working with Dock Windows',['../ui_dock.html',1,'ui']]],
  ['docks_20amp_20toolbars_40',['Showing/Hiding Docks &amp;amp; Toolbars',['../ui_dock.html#ui_docs_show',1,'']]],
  ['document_20interface_41',['Multiple Document Interface',['../ui_mdi.html',1,'ui']]],
  ['documentation_42',['Documentation',['../bm_class.html#bm_class-doc',1,'Class Documentation'],['../sm_statechart.html#sm_statechart-doc',1,'Documentation'],['../ce_comment.html#ce_comment-doc',1,'Generating Comments from Documentation'],['../sm_state.html#sm_state-doc',1,'State Documentation']]],
  ['does_20it_20do_43',['What does it do?',['../index.html#ab_goals',1,'']]],
  ['does_20it_20look_44',['How does it look?',['../index.html#ab_look',1,'']]],
  ['downloading_20additional_20files_45',['Downloading Additional Files',['../gs_tut.html#gs_tut_dwnld',1,'']]],
  ['downloading_20amp_20installing_20qm_46',['Downloading &amp;amp; Installing QM',['../gs_get.html',1,'gs']]],
  ['downloading_20qm_20from_20github_47',['Downloading QM from GitHub',['../gs_get.html#gs_gh',1,'']]],
  ['downloading_20qm_20in_20qp_20bundle_48',['Downloading QM in QP-Bundle',['../gs_get.html#gs_bundle',1,'']]],
  ['dpp_20example_49',['Dining Philosophers Problem (DPP) Example',['../gs_exa.html#dpp',1,'']]],
  ['drag_20and_20drop_50',['Drag-and-Drop',['../ce_dir.html#ce_dir_drag',1,'']]],
  ['drag_20and_20drop_20into_20files_51',['Drag-and-Drop into Files',['../ui_explorer.html#ui_explorer_drag-code',1,'']]],
  ['drag_20and_20drop_20within_20the_20model_20explorer_52',['Drag-and-Drop within the Model Explorer',['../ui_explorer.html#ui_explorer_drag-model',1,'']]],
  ['drag_20n_20drop_53',['Creating Fully-Qualified Names by Drag-n-Drop',['../ce_gen.html#ce_drag-n-drop',1,'']]],
  ['drawing_20canvas_54',['The Drawing Canvas',['../bm_diagram.html#bm_diagram_canvas',1,'']]],
  ['drawing_20state_20machine_20diagram_55',['Drawing State Machine Diagram',['../gs_tut.html#gs_tut_draw',1,'']]],
  ['drop_56',['Drop',['../ce_gen.html#ce_drag-n-drop',1,'Creating Fully-Qualified Names by Drag-n-Drop'],['../ce_dir.html#ce_dir_drag',1,'Drag-and-Drop']]],
  ['drop_20into_20files_57',['Drag-and-Drop into Files',['../ui_explorer.html#ui_explorer_drag-code',1,'']]],
  ['drop_20within_20the_20model_20explorer_58',['Drag-and-Drop within the Model Explorer',['../ui_explorer.html#ui_explorer_drag-model',1,'']]],
  ['dynamic_20linking_59',['Dynamic Linking',['../qt_lgpl.html#qt_lgpl-dyn',1,'']]]
];
