name: qmcraft
version: '7.0.1'
summary: QM 应用
description: |
  QM snap package.
base: core22
grade: stable
confinement: classic

parts:
  qm-binary:
    # dump 插件简单拷贝整个 release 目录
    plugin: dump
    source: .
    organize:
      # 把 bin/qm、bin/libQt6Core.so.6 等都留在 bin/
      "bin/*": bin/
    # 如果 core22 已经自带 glibc ≥2.34/2.28，可直接依赖
    # stage-packages:
    #   - libstdc++6
    #   - libglib2.0-0
    #   - libc6

  # custom-glibc:
  #   plugin: nil
  #   # 从系统以外路径拉一个新 glibc 或者预先编译好的 tarball
  #   # 你需先准备一个 glibc-2.34.tar.gz 放到项目里
  #   source: ./glibc-2.34.tar.gz
  #   stage:
  #     - usr/lib/libc-2.34.so
  #     - usr/lib/ld-2.34.so
  #   stage-packages: []  # 不从 repos 拉
  #   prime: []

  # patch-binary:
  #   plugin: dump
  #   source: .
  #   override-build: |
  #     set -eux
  #     snapcraftctl build
  #     # 用 patchelf 修改动态链接器和 rpath
  #     for bin in bin/qm bin/qmc; do
  #       patchelf --set-interpreter $SNAP/custom-glibc/usr/lib/ld-2.34.so \
  #               --set-rpath '$SNAP/custom-glibc/usr/lib:$ORIGIN' $SNAPCRAFT_PART_BUILD/$bin
  #     done
  #   build-packages:
  #     - patchelf

apps:
  qm:
    command: bin/qm
    plugs: [desktop, x11, wayland, opengl]
    # environment:
      # 优先用自带 glibc/libQt
      # LD_LIBRARY_PATH: $SNAP/custom-glibc/usr/lib:$SNAP/bin
