name: qm
version: '7.0.1'
summary: QM 应用
description: |
  QM snap package.
base: core22
grade: stable
confinement: classic

parts:
  qm-binary:
    plugin: dump
    source: ./qm
    # organize:
    #   "bin/*": bin/
    #   "Resources/*": Resources/
    #   "html/*": html/
    build-packages:
      - patchelf
    stage-packages:
      - libegl1
      - libgl1
      - libx11-6
      - libfontconfig1
      - libxkbcommon0
      - libxcb1
      - libxcb-cursor0
      - libxcb-icccm4
      - libxcb-image0
      - libxcb-keysyms1
      - libxcb-randr0
      - libxcb-render-util0
      - libxcb-render0
      - libxcb-shape0
      - libxcb-shm0
      - libxcb-sync1
      - libxcb-xfixes0
      - libxcb-xkb1
      - libxkbcommon-x11-0

    override-prime: |
      snapcraftctl prime

      # 修改 bin 目录权限为 755 (rwxr-xr-x)
      chmod -R 755 $SNAPCRAFT_PRIME/bin

      # 处理可执行文件：设置解释器和rpath
      for f in $SNAPCRAFT_PRIME/bin/qm $SNAPCRAFT_PRIME/bin/qmc; do
        if [ -f "$f" ]; then
          patchelf --set-interpreter /snap/core22/current/lib64/ld-linux-x86-64.so.2 \
                  --set-rpath '$ORIGIN:/snap/core22/current/lib/x86_64-linux-gnu' \
                  "$f"
        fi
      done
      
      # 处理共享库：只设置rpath，不设置解释器
      for f in $SNAPCRAFT_PRIME/bin/*.so* $SNAPCRAFT_PRIME/bin/platforms/libqxcb.so; do
        if [ -f "$f" ]; then
          patchelf --set-rpath '$ORIGIN:/snap/core22/current/lib/x86_64-linux-gnu' "$f"
        fi
      done

apps:
  qm:
    command: bin/qm
    plugs: [desktop, x11, wayland, opengl]
    environment:
      LD_LIBRARY_PATH: $SNAP/usr/lib/x86_64-linux-gnu:$SNAP/bin:$LD_LIBRARY_PATH
  qmc:
    command: bin/qmc
    plugs: [desktop, x11, wayland, opengl]
    environment:
      LD_LIBRARY_PATH: $SNAP/usr/lib/x86_64-linux-gnu:$SNAP/bin:$LD_LIBRARY_PATH